networks:
  telegram:
    name: telegram  # Custom network for communication between containers

services:
  #Launches dev version of docker
  portfolium_dev:
    build:
        context: .
        dockerfile: ./Docker/dev/Dockerfile
    container_name: portfolium_dev
    user: root
    env_file:
      - ./.env
    hostname: "localhost"
    ports:
      - "8000:8000"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./setup.py:/app/manage.py
      - ./portfolium:/app/portfolium
    command: ./entrypoint.sh
    tty: true

volumes:
  data: