// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ekinbasarkomur

//@version=5
indicator("DSS with Alert", overlay=false)

// Inputs
PDS = input.int(10, minval=1, title="Periods")
EMAlen = input.int(9, minval=1, title="EMA Length")
TriggerLen = input.int(5, minval=1, title="Trigger Length")
Overbought = input.int(80, minval=1, title="Overbought Level")
Oversold = input.int(20, minval=1, title="Oversold Level")
res = input.timeframe("", title="Resolution")


// Fetch higher resolution data for the selected timeframe
calc_dss_trig()=>
    // Calculate DSS
    xPreCalc = ta.ema(ta.stoch(close, high, low, PDS), EMAlen)
    xDSS = ta.ema(ta.stoch(xPreCalc, xPreCalc, xPreCalc, PDS), EMAlen)
    xTrigger = ta.ema(xDSS, TriggerLen)

    [xDSS, xTrigger]

[DSS, Trigger] = request.security(syminfo.tickerid, res, calc_dss_trig())


// Plot DSS and Trigger
plot(DSS, color=color.blue, title="DSS")
plot(Trigger, color=color.red, title="Trigger")

// Horizontal Lines for Overbought and Oversold Levels
hline(Overbought, "Overbought", color=color.green)
hline(Oversold, "Oversold", color=color.red)

// Check if a new bar has formed
is_new_bar = ta.change(time) != 0

// Trigger alert on every new bar
if (is_new_bar)
    alert_message = '{"symbol": "' + syminfo.tickerid + '", "DSS": ' + str.tostring(DSS, "#.#") + '}'
    alert(alert_message, alert.freq_once_per_bar)