name: Run phpMyAdmin

on:
    workflow_dispatch:


env:
    AWS_REGION: eu-central-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
    SERVER_PUBLIC_IP: ${{ secrets.AWS_PUBLIC_KEY }}
    DB_HOST: ${{ secrets.DB_HOST }}

jobs:
    run-phpmyadmin:
        runs-on: ubuntu-latest

        steps:
          
          - name: Run phpMyAdmin
            uses: appleboy/ssh-action@master
            with:
              host: ${{ env.SERVER_PUBLIC_IP }}
              username: ec2-user
              key: ${{ env.PRIVATE_SSH_KEY }}
              envs: PRIVATE_SSH_KEY, DB_HOST
              script: |-
                sudo yum update
                sudo docker pull phpmyadmin
                
                sudo docker run -d --rm \
                    --name pmyadmin \
                    -p 8000:80 \
                    --network strategie_meister \
                    --link ${DB_HOST}:db \
                    phpmyadmin